# Configuração da Base de Dados (Spring Boot Native)
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:tub}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER:tub_user}
spring.datasource.password=${DB_PASS:tub_pass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuração de Logs
logging.level.org.springframework.web=INFO
logging.level.pt.uminho.dai.pgu=DEBUG

# Servidor
server.port=8080
server.error.include-message=always
