services:
  mysql:
    image: mysql:8.0
    container_name: tub_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?Definir MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME:-tub}
      MYSQL_USER: ${DB_USER:-tub_user}
      MYSQL_PASSWORD: ${DB_PASS:?Definir DB_PASS}
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - tub_data:/var/lib/mysql

volumes:
  tub_data: